@baseurl = http://localhost:8000/api
@token = eyJhbGciOiJIUzI1NiJ9.ODM.6aCKC4ZPNIs-JZB2U6x0CaZ518jwvlwr9OzVZjU8mwY
###
// **** USER APIs
// -----USER-------- Register (Create)
POST {{baseurl}}/user HTTP/1.1
content-type: application/json

{
    "email": "jan@25.com",
    "password" : "password"
}

###

// -----USER-------- Login (Read)
GET {{baseurl}}/user HTTP/1.1
content-type: application/json

{
    "email": "jan@25.com",
    "password" : "password"
}

###

// -----USER-------- Edit Account (Update)

###

// -----USER-------- Delete (Delete)
DELETE {{baseurl}}/user HTTP/1.1
content-type: application/json
auth-token: {{token}}

{

}

###

// **** NOTE APIs
// -----NOTE-------- Create (Create)
POST {{baseurl}}/note HTTP/1.1
content-type: application/json
auth-token: {{token}}

{
    "title" : "Title #4",
    "description" : "LoremSipsumB,aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaagrdgfrdegertgergerg888888888LoremSipsumB,aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaagrdgfrdegertgergerg888888888LoremSipsumB,aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaagrdgfrdegertgergerg8888888885555555555LoremSipsumB,aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaagrdgfrdegertgergerg888888888LoremSipsumB,aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaagrdgfrdegertgergerg888888888LoremSipsumB,aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaagrdgfrdegertgergerg8888888885555555555",
    "category" : "Testing",
    "tags" : "FourScript, JotFox"
}

###

// -----NOTE-------- Show (Read)
GET {{baseurl}}/note HTTP/1.1
content-type: application/json
auth-token: {{token}}

{

}

###

// -----NOTE-------- Edit (Update)
PUT {{baseurl}}/note HTTP/1.1
content-type: application/json
auth-token: {{token}}

{
    "noteID" : 11,
    "title" : "EDITED title",
    "description" : "EDITED description",
    "category" : "EDITED",
    "tags" : "Bing, Bang, Boom"
}

###

// -----NOTE-------- Delete (Delete)
DELETE {{baseurl}}/note HTTP/1.1
content-type: application/json
auth-token: {{token}}

{
    "noteID" : 11
}